### ISSUE TITLE
Can I use this software for other genomes?

### ISSUE THREAD

**Issue by hanshanmengqi** [Tuteja-Lab/UnsupervisedPeakCaller#5]
Hello,

It's exciting software. 

Now I have a question. If my understanding is right, the supported genome is mm10 (Ensembl) and hg38 (Ensembl).

Can I use it for other genomes? (for example, tomato)

Thank you for your time.
Han

**Comment by hhvu0102** [comment]
Hi Han,

Thanks for your interest. Besides mouse and human, we have tested the software with only zebrafish genome, so I'm not sure how it will perform on genomes such as tomato. If RCL is run on non-mouse or non-human genome, one issue that I can think of is that the chromosome names of these genomes may not be standardized and make it difficult for the preprocessing steps.

We are currently working on RCL extension and hopefully will be able to include a wide variety of genomes soon.

**Comment by malcook** [comment]
Hi.  How did RCL perform on zebrafish?  Did you contrast its performance with other methods as done in the paper?
