### ISSUE TITLE
How does RCL compare with Genrich

### ISSUE THREAD

**Issue by malcook** [Tuteja-Lab/UnsupervisedPeakCaller#6]
Not really an Issue, but a question.

Was https://github.com/jsh58/Genrich considered as a method to contrast against in your paper?  If so, why was it rejected?

FWIW I have used it as recommended by Harvard's [ATAC\-seq Guidelines](https://informatics.fas.harvard.edu/atac-seq-guidelines.html) for peak calling in ATAC-Seq with 3 replicates in zebrafish with generally good success.

(Thanks for RCL & congrats on the paper!)

**Comment by hhvu0102** [comment]
Hello,

Thank you for your question. From my understanding, Genrich is good if one is interested in the Tn5 cut sites. RCL’s general goals do not focus on the cut sites, but we infer the regions between cut sites. In case one wants the regions between cut sites, Genrich performs similarly to MACS, which was included in our paper.

Nevertheless, Genrich is definitely an interesting approach and we will try to benchmark RCL against Genrich soon.
